name: Generate Podcast Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.10'
      - name: install deps
        run: | 
          python -m pip install --upgrade pip
          pip instal pyyaml
      - name: run feed generator
        run: python feed.py
      - name: push repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "modified feed"
          git push
      
      
    
